-- Create home_cycles table
DROP TABLE IF EXISTS home_cycles;

CREATE TABLE home_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    manual_name TEXT,
    home_cycle_id TEXT
);

-- Allow unrestricted access (since your app operates without auth)
ALTER TABLE home_cycles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous select on home_cycles"
ON home_cycles FOR SELECT
TO anon
USING (true);

CREATE POLICY "Allow anonymous insert on home_cycles"
ON home_cycles FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "Allow anonymous delete on home_cycles"
ON home_cycles FOR DELETE
TO anon
USING (true);
